version: '3.7'
services:
  mongodb:
    image: mongo:4.4.5
    expose:
      - '27017'
    ports: 
      - '27017:27017'
    networks:
      - chatapp
  redis:
    image: redis:alpine3.13
    networks:
      - chatapp
    expose: 
      - '6379'
    ports: 
      - '6379:6379'
  api:
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - redis
      - mongodb
    networks:
      - chatapp
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=developement
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  chatapp:
