version: '3.7'
services:
  mongodb:
    image: mongo:4.4.5
  redis:
    image: redis:alpine3.13
  api:
    build:
      context: .
      target: production
    command: npm run start:prod
    depends_on:
      - redis
      - mongodb
    ports:
      - '${EXPRESS_PORT}:${EXPRESS_PORT}'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
