version: '3'
services:
  mongodb:
    image: mongo
    expose:
      - '27017'
    networks:
      - chatapp
  redis:
    image: redis
    networks:
      - chatapp
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run start:dev
    depends_on:
      - redis
      - mongodb
    networks:
      - chatapp
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=developement
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  chatapp:
